version: '3.9'
services:
  elasticsearch:
    build:
      context: ELASTICSEARCH/
      dockerfile: Dockerfile
    ports:
      - 9200:9200
    volumes:
      - "es-data:/usr/share/elasticsearch/data"
    networks:
      - ELK
  kibana:
      build:
        context: Kibana/
        dockerfile: Dockerfile
      ports:
        - 5601:5601
      volumes:
        - "kibana-data:/usr/share/kibana/data"
      environment:
        - 'ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]'
      networks:
        - ELK
      depends_on:
        - elasticsearch

networks:
  ELK:
    driver: bridge
volumes:
  es-data:
  kibana-data:
