version: '3'
services:
  elasticsearch:
    build:
      context: ELASTICSEARCH/
      dockerfile: Dockerfile
    ports:
      - 9200:9200
    networks:
        - ELK
    volumes:
      - "els-data:/usr/share/elasticsearch/data"
      - "cert_v:/usr/share/elasticsearch/config/certs"
    # environment:
  # kibana:
  #     build:
  #       context: Kibana/
  #       dockerfile: Dockerfile
  #     ports:
  #       - 5601:5601
  #     networks:
  #       - ELK
  #     environment:
  #       - "ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'"
  #       # - "ELASTICSEARCH_USERNAME: 'elastic'"
  #       # - "server.host: 0.0.0.0"
  #       # - "ELASTICSEARCH_PASSWORD: 'pass123'"
  #     volumes:
  #       - "kibana-data:/usr/share/kibana/data"

networks:
  ELK:
    driver: bridge
volumes:
  els-data:
  cert_v:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/cert'
  # kibana-data:
