FROM docker.elastic.co/elasticsearch/elasticsearch:8.17.0
USER root
WORKDIR /usr/share/elasticsearch
COPY setup.sh .
COPY elasticsearch.yml /usr/share/elasticsearch/config/elastic.yml
RUN chmod +x /usr/share/elasticsearch/setup.sh
CMD [ "/usr/share/elasticsearch/setup.sh" ]